### ISSUE TITLE
As easy as serde_json : could I use it to read files?

### ISSUE THREAD

**Issue by ianxek** [imbolc/csv-line#1]
Hi,

Very glad to have found your crate that makes it as easy as serde_json to read csv from &str notably. But does your insistence on single line mean I should not use the very nice easy interface you provide to read files line by line?

**Comment by imbolc** [comment]
You totally can do this. Though if performance isn't your concern, you probably want to use de facto standard `csv` crate with `serde`, here's [an example](https://docs.rs/csv/latest/csv/#example-with-serde).

**Comment by ianxek** [comment]
Yes, I had seen that, but it's not as easy to use as your interface, and less performant, so the choice is easy, no?

**Comment by imbolc** [comment]
Yes, I guess if there's need in richer functionality csv crate provides, I'd start with a simpler option too
