### ISSUE TITLE
Separator?

### ISSUE THREAD

**Issue by ianxek** [imbolc/csv-line#2]
How can I specify another separator than comma?

**Comment by imbolc** [comment]
https://docs.rs/csv-line/latest/csv_line/struct.CSVLine.html#method.delimiter

**Comment by ianxek** [comment]
Yes, I since had found the test giving an example:

https://github.com/imbolc/csv-line/blob/dfb4f11835673ce404e1bcc79911833c329485af/src/lib.rs#L135
